[[constraint]]
    name = "github.com/xgfone/go-config"
    version = "v3.0.0"

[[constraint]]
    name = "github.com/xgfone/go-tools"
    version = "v2.0.0"

[[constraint]]
    name = "github.com/golang/glog"
    branch = "master"

[[constraint]]
    name = "github.com/samuel/go-zookeeper"
    revision = "9a96098268ef555eb1f04d8b1ee813d0a87e5089"
